Fonction push récupérée
Problème 1 : $ git remote add origin https://github.com/Develoqer/gittrain.git
fatal: remote origin already exists.

Problème 2 :  
$ git push -u origin master
To https://github.com/Develoqer/git-training.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/Develoqer/git-training.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Solution 👍  créer une origin2 puis reconfigurer le lien avec la commande set-url

$ git remote -v
origin  https://github.com/Develoqer/git-training.git (fetch)
origin  https://github.com/Develoqer/git-training.git (push)

git remote set-url origin https://github.com/Develoqer/gittrain.git